language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
script:
  - make test
after_success:
  - make coverage
  - coveralls
